# Importing Libraries

In [1]:
import pandas as pd

# IMDB in CSV format

In [2]:
df=pd.read_csv("IMDB.csv")

In [3]:
df

,X,Title,Rating,TotalVotes,Genre1,Genre2,Genre3,MetaCritic,Budget,Runtime,...,Votes45A,Votes45AM,Votes45AF,VotesIMDB,Votes1000,VotesUS,VotesnUS,Domestic,Foreign,Worldwide
0,1,12 Years a Slave (2013),8.1,496092,Biography,Drama,History,96.0,20000000.0,134 min,...,7.8,7.8,8.1,8.0,7.7,8.3,8.0,"$56,671,993",131061209,"$187,733,202"
1,2,127 Hours (2010),7.6,297075,Adventure,Biography,Drama,82.0,18000000.0,94 min,...,7.3,7.3,7.5,7.6,7.0,7.7,7.6,"$18,335,230",42403567,"$60,738,797"
2,3,50/50 (2011),7.7,283935,Comedy,Drama,Romance,72.0,8000000.0,100 min,...,7.4,7.4,7.5,7.4,7.0,7.9,7.6,"$35,014,192",4173591,"$39,187,783"
3,4,About Time (2013),7.8,225412,Comedy,Drama,Fantasy,NaN,12000000.0,123 min,...,7.6,7.5,7.8,7.7,6.9,7.8,7.7,"$15,322,921",71777528,"$87,100,449"
4,5,Amour (2012),7.9,76121,Drama,Romance,NaN,94.0,8900000.0,127 min,...,7.9,7.8,8.1,6.6,7.2,7.9,7.8,"$6,739,492",13100000,"$19,839,492"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,114,Whiplash (2014),8.5,492285,Drama,Music,NaN,88.0,3300000.0,107 min,...,8.1,8.1,8.2,8.7,8.0,8.6,8.4,"$13,092,000",35890041,"$48,982,041"
113,115,Wreck-It Ralph (2012),7.7,295125,Animation,Adventure,Comedy,72.0,165000000.0,NaN,...,7.4,7.4,7.5,7.4,7.2,7.9,7.6,"$189,422,889",281800000,"$471,222,889"
114,116,X-Men: Days of Future Past (2014),8.0,560736,Action,Adventure,Sci-Fi,74.0,200000000.0,132 min,...,7.7,7.7,7.9,7.5,7.4,8.1,7.9,"$233,921,534",513941241,"$747,862,775"
115,117,X-Men: First Class (2011),7.8,556713,Action,Adventure,Sci-Fi,65.0,160000000.0,132 min,...,7.6,7.5,7.7,7.6,7.3,7.8,7.7,"$146,408,305",207215819,"$353,624,124"
116,118,Zootopia (2016),8.1,309474,Animation,Adventure,Comedy,78.0,150000000.0,108 min,...,7.8,7.8,8.1,7.7,7.6,8.0,8.0,"$341,268,248",682515947,"$1,023,784,195"

In [4]:
df.head(20)

,X,Title,Rating,TotalVotes,Genre1,Genre2,Genre3,MetaCritic,Budget,Runtime,...,Votes45A,Votes45AM,Votes45AF,VotesIMDB,Votes1000,VotesUS,VotesnUS,Domestic,Foreign,Worldwide
0,1,12 Years a Slave (2013),8.1,496092,Biography,Drama,History,96.0,20000000.0,134 min,...,7.8,7.8,8.1,8.0,7.7,8.3,8.0,"$56,671,993",131061209,"$187,733,202"
1,2,127 Hours (2010),7.6,297075,Adventure,Biography,Drama,82.0,18000000.0,94 min,...,7.3,7.3,7.5,7.6,7.0,7.7,7.6,"$18,335,230",42403567,"$60,738,797"
2,3,50/50 (2011),7.7,283935,Comedy,Drama,Romance,72.0,8000000.0,100 min,...,7.4,7.4,7.5,7.4,7.0,7.9,7.6,"$35,014,192",4173591,"$39,187,783"
3,4,About Time (2013),7.8,225412,Comedy,Drama,Fantasy,NaN,12000000.0,123 min,...,7.6,7.5,7.8,7.7,6.9,7.8,7.7,"$15,322,921",71777528,"$87,100,449"
4,5,Amour (2012),7.9,76121,Drama,Romance,NaN,94.0,8900000.0,127 min,...,7.9,7.8,8.1,6.6,7.2,7.9,7.8,"$6,739,492",13100000,"$19,839,492"
5,6,Argo (2012),7.7,486840,Action,Biography,Drama,86.0,44500000.0,120 min,...,7.7,7.7,8.0,8.1,7.2,8.0,7.6,"$136,025,503",96300000,"$232,325,503"
6,7,Arrival (2016),8.0,370842,Drama,Mystery,Sci-Fi,81.0,47000000.0,116 min,...,7.6,7.6,7.7,8.3,7.3,8.0,7.9,"$100,546,139",102842047,"$203,388,186"
7,9,Before Midnight (2013),7.9,106553,Drama,Romance,NaN,94.0,3000000.0,109 min,...,7.3,7.4,7.2,8.5,7.0,8.0,7.9,"$8,114,627",3061842,"$11,176,469"
8,10,Big Hero 6 (2014),7.8,315485,Animation,Action,Adventure,74.0,165000000.0,NaN,...,7.6,7.6,7.9,7.9,7.2,7.9,7.7,"$222,527,828",435290784,"$657,818,612"
9,11,Birdman or (The Unexpected Virtue of Ignorance...,7.8,448725,Comedy,Drama,NaN,88.0,18000000.0,119 min,...,7.2,7.3,7.0,7.8,7.1,7.9,7.7,"$42,340,598",60874496,"$103,215,094"
10,12,Black Swan (2010),8.0,587893,Drama,Thriller,NaN,79.0,13000000.0,108 min,...,7.5,7.5,7.4,7.9,7.6,8.0,8.0,"$106,954,678",222443368,"$329,398,046"
11,13,Boyhood (2014),7.9,290327,Drama,NaN,NaN,100.0,4000000.0,165 min,...,7.7,7.7,7.7,8.2,7.2,8.0,7.9,"$25,352,281",19143000,"$44,495,281"
12,14,Bridge of Spies (2015),7.6,223756,Drama,History,Thriller,81.0,40000000.0,142 min,...,7.7,7.6,7.9,7.7,7.4,7.7,7.5,"$72,313,754",93164594,"$165,478,348"
13,15,Captain America: Civil War (2016),7.9,431555,Action,Adventure,Sci-Fi,75.0,250000000.0,147 min,...,7.6,7.6,7.9,7.7,7.5,8.1,7.7,"$408,084,349",745220146,"$1,153,304,495"
14,16,Captain America: The Winter Soldier (2014),7.8,552706,Action,Adventure,Sci-Fi,70.0,170000000.0,136 min,...,7.7,7.6,7.8,7.6,7.5,8.1,7.5,"$259,766,572",454497695,"$714,264,267"
15,17,Captain Fantastic (2016),7.9,115194,Comedy,Drama,NaN,72.0,5000000.0,NaN,...,7.7,7.6,7.9,8.5,6.8,7.8,7.8,"$5,879,736",n/a,"$5,879,736"
16,18,Captain Phillips (2013),7.8,350818,Biography,Drama,Thriller,83.0,55000000.0,134 min,...,7.7,7.7,8.0,8.0,7.4,7.8,7.8,"$107,100,855",111690956,"$218,791,811"
17,19,Creed (2015),7.6,179795,Drama,Sport,NaN,82.0,35000000.0,133 min,...,7.3,7.3,7.5,7.8,7.1,7.9,7.5,"$109,767,581",63800000,"$173,567,581"
18,20,Dallas Buyers Club (2013),8.0,357641,Biography,Drama,NaN,84.0,5000000.0,117 min,...,7.8,7.8,8.0,7.9,7.2,8.0,7.9,"$27,298,285",27900000,"$55,198,285"
19,21,Dawn of the Planet of the Apes (2014),7.6,349646,Action,Adventure,Drama,79.0,170000000.0,130 min,...,7.4,7.4,7.4,7.2,7.4,7.8,7.5,"$208,545,589",502098977,"$710,644,566"

In [5]:
df.tail()

,X,Title,Rating,TotalVotes,Genre1,Genre2,Genre3,MetaCritic,Budget,Runtime,...,Votes45A,Votes45AM,Votes45AF,VotesIMDB,Votes1000,VotesUS,VotesnUS,Domestic,Foreign,Worldwide
112,114,Whiplash (2014),8.5,492285,Drama,Music,NaN,88.0,3300000.0,107 min,...,8.1,8.1,8.2,8.7,8.0,8.6,8.4,"$13,092,000",35890041,"$48,982,041"
113,115,Wreck-It Ralph (2012),7.7,295125,Animation,Adventure,Comedy,72.0,165000000.0,NaN,...,7.4,7.4,7.5,7.4,7.2,7.9,7.6,"$189,422,889",281800000,"$471,222,889"
114,116,X-Men: Days of Future Past (2014),8.0,560736,Action,Adventure,Sci-Fi,74.0,200000000.0,132 min,...,7.7,7.7,7.9,7.5,7.4,8.1,7.9,"$233,921,534",513941241,"$747,862,775"
115,117,X-Men: First Class (2011),7.8,556713,Action,Adventure,Sci-Fi,65.0,160000000.0,132 min,...,7.6,7.5,7.7,7.6,7.3,7.8,7.7,"$146,408,305",207215819,"$353,624,124"
116,118,Zootopia (2016),8.1,309474,Animation,Adventure,Comedy,78.0,150000000.0,108 min,...,7.8,7.8,8.1,7.7,7.6,8.0,8.0,"$341,268,248",682515947,"$1,023,784,195"

In [6]:
df = pd.read_csv('IMDB.csv',  usecols=['Title', 'Rating', 'Worldwide'])

In [7]:
df.head(100)

                        Title  Rating      Worldwide
0     12 Years a Slave (2013)     8.1  $187,733,202
1            127 Hours (2010)     7.6   $60,738,797
2                50/50 (2011)     7.7   $39,187,783
3           About Time (2013)     7.8   $87,100,449
4                Amour (2012)     7.9   $19,839,492
..                        ...     ...            ...
95  The Imitation Game (2014)     8.1  $233,555,708
96   The King's Speech (2010)     8.0  $414,211,549
97      The Lego Movie (2014)     7.8  $469,160,692
98   The Little Prince (2015)     7.8   $97,571,250
99         The Martian (2015)     8.0  $630,161,890

[100 rows x 3 columns]

In [8]:
df = pd.read_csv('IMDB.csv',  na_values=[''])

In [9]:
df

,X,Title,Rating,TotalVotes,Genre1,Genre2,Genre3,MetaCritic,Budget,Runtime,...,Votes45A,Votes45AM,Votes45AF,VotesIMDB,Votes1000,VotesUS,VotesnUS,Domestic,Foreign,Worldwide
0,1,12 Years a Slave (2013),8.1,496092,Biography,Drama,History,96.0,20000000.0,134 min,...,7.8,7.8,8.1,8.0,7.7,8.3,8.0,"$56,671,993",131061209,"$187,733,202"
1,2,127 Hours (2010),7.6,297075,Adventure,Biography,Drama,82.0,18000000.0,94 min,...,7.3,7.3,7.5,7.6,7.0,7.7,7.6,"$18,335,230",42403567,"$60,738,797"
2,3,50/50 (2011),7.7,283935,Comedy,Drama,Romance,72.0,8000000.0,100 min,...,7.4,7.4,7.5,7.4,7.0,7.9,7.6,"$35,014,192",4173591,"$39,187,783"
3,4,About Time (2013),7.8,225412,Comedy,Drama,Fantasy,NaN,12000000.0,123 min,...,7.6,7.5,7.8,7.7,6.9,7.8,7.7,"$15,322,921",71777528,"$87,100,449"
4,5,Amour (2012),7.9,76121,Drama,Romance,NaN,94.0,8900000.0,127 min,...,7.9,7.8,8.1,6.6,7.2,7.9,7.8,"$6,739,492",13100000,"$19,839,492"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,114,Whiplash (2014),8.5,492285,Drama,Music,NaN,88.0,3300000.0,107 min,...,8.1,8.1,8.2,8.7,8.0,8.6,8.4,"$13,092,000",35890041,"$48,982,041"
113,115,Wreck-It Ralph (2012),7.7,295125,Animation,Adventure,Comedy,72.0,165000000.0,NaN,...,7.4,7.4,7.5,7.4,7.2,7.9,7.6,"$189,422,889",281800000,"$471,222,889"
114,116,X-Men: Days of Future Past (2014),8.0,560736,Action,Adventure,Sci-Fi,74.0,200000000.0,132 min,...,7.7,7.7,7.9,7.5,7.4,8.1,7.9,"$233,921,534",513941241,"$747,862,775"
115,117,X-Men: First Class (2011),7.8,556713,Action,Adventure,Sci-Fi,65.0,160000000.0,132 min,...,7.6,7.5,7.7,7.6,7.3,7.8,7.7,"$146,408,305",207215819,"$353,624,124"
116,118,Zootopia (2016),8.1,309474,Animation,Adventure,Comedy,78.0,150000000.0,108 min,...,7.8,7.8,8.1,7.7,7.6,8.0,8.0,"$341,268,248",682515947,"$1,023,784,195"

In [10]:
df.shape

(117, 58)

# IMDB Excel

In [11]:
df_excel=pd.read_excel("IMDB.xlsx")

In [12]:
df_excel

,X,Title,Rating,TotalVotes,Genre1,Genre2,Genre3,MetaCritic,Budget,Runtime,...,Votes45A,Votes45AM,Votes45AF,VotesIMDB,Votes1000,VotesUS,VotesnUS,Domestic,Foreign,Worldwide
0,1,12 Years a Slave (2013),8.1,496092,Biography,Drama,History,96.0,20000000.0,134 min,...,7.8,7.8,8.1,8.0,7.7,8.3,8.0,"$56,671,993",131061209,"$187,733,202"
1,2,127 Hours (2010),7.6,297075,Adventure,Biography,Drama,82.0,18000000.0,94 min,...,7.3,7.3,7.5,7.6,7.0,7.7,7.6,"$18,335,230",42403567,"$60,738,797"
2,3,50/50 (2011),7.7,283935,Comedy,Drama,Romance,72.0,8000000.0,100 min,...,7.4,7.4,7.5,7.4,7.0,7.9,7.6,"$35,014,192",4173591,"$39,187,783"
3,4,About Time (2013),7.8,225412,Comedy,Drama,Fantasy,NaN,12000000.0,123 min,...,7.6,7.5,7.8,7.7,6.9,7.8,7.7,"$15,322,921",71777528,"$87,100,449"
4,5,Amour (2012),7.9,76121,Drama,Romance,NaN,94.0,8900000.0,127 min,...,7.9,7.8,8.1,6.6,7.2,7.9,7.8,"$6,739,492",13100000,"$19,839,492"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,114,Whiplash (2014),8.5,492285,Drama,Music,NaN,88.0,3300000.0,107 min,...,8.1,8.1,8.2,8.7,8.0,8.6,8.4,"$13,092,000",35890041,"$48,982,041"
113,115,Wreck-It Ralph (2012),7.7,295125,Animation,Adventure,Comedy,72.0,165000000.0,NaN,...,7.4,7.4,7.5,7.4,7.2,7.9,7.6,"$189,422,889",281800000,"$471,222,889"
114,116,X-Men: Days of Future Past (2014),8.0,560736,Action,Adventure,Sci-Fi,74.0,200000000.0,132 min,...,7.7,7.7,7.9,7.5,7.4,8.1,7.9,"$233,921,534",513941241,"$747,862,775"
115,117,X-Men: First Class (2011),7.8,556713,Action,Adventure,Sci-Fi,65.0,160000000.0,132 min,...,7.6,7.5,7.7,7.6,7.3,7.8,7.7,"$146,408,305",207215819,"$353,624,124"
116,118,Zootopia (2016),8.1,309474,Animation,Adventure,Comedy,78.0,150000000.0,108 min,...,7.8,7.8,8.1,7.7,7.6,8.0,8.0,"$341,268,248",682515947,"$1,023,784,195"

In [13]:

df_excel = pd.read_excel('IMDB.xlsx', sheet_name=0)

In [14]:
df_excel

,X,Title,Rating,TotalVotes,Genre1,Genre2,Genre3,MetaCritic,Budget,Runtime,...,Votes45A,Votes45AM,Votes45AF,VotesIMDB,Votes1000,VotesUS,VotesnUS,Domestic,Foreign,Worldwide
0,1,12 Years a Slave (2013),8.1,496092,Biography,Drama,History,96.0,20000000.0,134 min,...,7.8,7.8,8.1,8.0,7.7,8.3,8.0,"$56,671,993",131061209,"$187,733,202"
1,2,127 Hours (2010),7.6,297075,Adventure,Biography,Drama,82.0,18000000.0,94 min,...,7.3,7.3,7.5,7.6,7.0,7.7,7.6,"$18,335,230",42403567,"$60,738,797"
2,3,50/50 (2011),7.7,283935,Comedy,Drama,Romance,72.0,8000000.0,100 min,...,7.4,7.4,7.5,7.4,7.0,7.9,7.6,"$35,014,192",4173591,"$39,187,783"
3,4,About Time (2013),7.8,225412,Comedy,Drama,Fantasy,NaN,12000000.0,123 min,...,7.6,7.5,7.8,7.7,6.9,7.8,7.7,"$15,322,921",71777528,"$87,100,449"
4,5,Amour (2012),7.9,76121,Drama,Romance,NaN,94.0,8900000.0,127 min,...,7.9,7.8,8.1,6.6,7.2,7.9,7.8,"$6,739,492",13100000,"$19,839,492"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,114,Whiplash (2014),8.5,492285,Drama,Music,NaN,88.0,3300000.0,107 min,...,8.1,8.1,8.2,8.7,8.0,8.6,8.4,"$13,092,000",35890041,"$48,982,041"
113,115,Wreck-It Ralph (2012),7.7,295125,Animation,Adventure,Comedy,72.0,165000000.0,NaN,...,7.4,7.4,7.5,7.4,7.2,7.9,7.6,"$189,422,889",281800000,"$471,222,889"
114,116,X-Men: Days of Future Past (2014),8.0,560736,Action,Adventure,Sci-Fi,74.0,200000000.0,132 min,...,7.7,7.7,7.9,7.5,7.4,8.1,7.9,"$233,921,534",513941241,"$747,862,775"
115,117,X-Men: First Class (2011),7.8,556713,Action,Adventure,Sci-Fi,65.0,160000000.0,132 min,...,7.6,7.5,7.7,7.6,7.3,7.8,7.7,"$146,408,305",207215819,"$353,624,124"
116,118,Zootopia (2016),8.1,309474,Animation,Adventure,Comedy,78.0,150000000.0,108 min,...,7.8,7.8,8.1,7.7,7.6,8.0,8.0,"$341,268,248",682515947,"$1,023,784,195"

In [15]:
type(df_excel)

pandas.core.frame.DataFrame

In [16]:
xls_file = pd.ExcelFile('IMDB.xlsx')

In [17]:
xls_file

In [18]:
type(xls_file)

pandas.io.excel._base.ExcelFile

In [19]:
xls_file.sheet_names

['movies', 'by genre']

In [20]:

df_excel = pd.read_excel('IMDB.xlsx', sheet_name=0, index_col='Title')

In [21]:
df_excel

,X,Rating,TotalVotes,Genre1,Genre2,Genre3,MetaCritic,Budget,Runtime,CVotes10,...,Votes45A,Votes45AM,Votes45AF,VotesIMDB,Votes1000,VotesUS,VotesnUS,Domestic,Foreign,Worldwide
Title,,,,,,,,,,,,,,,,,,,,,
12 Years a Slave (2013),1,8.1,496092,Biography,Drama,History,96.0,20000000.0,134 min,75556,...,7.8,7.8,8.1,8.0,7.7,8.3,8.0,"$56,671,993",131061209,"$187,733,202"
127 Hours (2010),2,7.6,297075,Adventure,Biography,Drama,82.0,18000000.0,94 min,28939,...,7.3,7.3,7.5,7.6,7.0,7.7,7.6,"$18,335,230",42403567,"$60,738,797"
50/50 (2011),3,7.7,283935,Comedy,Drama,Romance,72.0,8000000.0,100 min,28304,...,7.4,7.4,7.5,7.4,7.0,7.9,7.6,"$35,014,192",4173591,"$39,187,783"
About Time (2013),4,7.8,225412,Comedy,Drama,Fantasy,NaN,12000000.0,123 min,38556,...,7.6,7.5,7.8,7.7,6.9,7.8,7.7,"$15,322,921",71777528,"$87,100,449"
Amour (2012),5,7.9,76121,Drama,Romance,NaN,94.0,8900000.0,127 min,11093,...,7.9,7.8,8.1,6.6,7.2,7.9,7.8,"$6,739,492",13100000,"$19,839,492"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Whiplash (2014),114,8.5,492285,Drama,Music,NaN,88.0,3300000.0,107 min,110404,...,8.1,8.1,8.2,8.7,8.0,8.6,8.4,"$13,092,000",35890041,"$48,982,041"
Wreck-It Ralph (2012),115,7.7,295125,Animation,Adventure,Comedy,72.0,165000000.0,NaN,41980,...,7.4,7.4,7.5,7.4,7.2,7.9,7.6,"$189,422,889",281800000,"$471,222,889"
X-Men: Days of Future Past (2014),116,8.0,560736,Action,Adventure,Sci-Fi,74.0,200000000.0,132 min,91765,...,7.7,7.7,7.9,7.5,7.4,8.1,7.9,"$233,921,534",513941241,"$747,862,775"
X-Men: First Class (2011),117,7.8,556713,Action,Adventure,Sci-Fi,65.0,160000000.0,132 min,64428,...,7.6,7.5,7.7,7.6,7.3,7.8,7.7,"$146,408,305",207215819,"$353,624,124"
Zootopia (2016),118,8.1,309474,Animation,Adventure,Comedy,78.0,150000000.0,108 min,53626,...,7.8,7.8,8.1,7.7,7.6,8.0,8.0,"$341,268,248",682515947,"$1,023,784,195"

# IMDB Html

In [22]:
movies=pd.read_html("IMDB.html")

In [23]:
movies[0]

,0,1,2,3,4,5,6,7,8,9,...,48,49,50,51,52,53,54,55,56,57
0,X,Title,Rating,TotalVotes,Genre1,Genre2,Genre3,MetaCritic,Budget,Runtime,...,Votes45A,Votes45AM,Votes45AF,VotesIMDB,Votes1000,VotesUS,VotesnUS,Domestic,Foreign,Worldwide
1,1,12 Years a Slave(2013),8.1,496,092,Biography,Drama,History,96,20,...,8.0,7.9,8.0,7.8,7.8,8.1,8.0,7.7,8.3,8.0
2,2,127 Hours (2010),7.6,297,075,Adventure,Biography,Drama,82,18,...,7.5,7.5,7.5,7.3,7.3,7.5,7.6,7.0,7.7,7.6
3,3,50/50 (2011),7.7,283,935,Comedy,Drama,Romance,72,8,...,7.6,7.6,7.6,7.4,7.4,7.5,7.4,7.0,7.9,7.6
4,4,About Time (2013),7.8,225,412,Comedy,Drama,Fantasy,NaN,12,...,7.6,7.6,7.7,7.6,7.5,7.8,7.7,6.9,7.8,7.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,114,Whiplash (2014),8.5,492,285,Drama,Music,NaN,88,3,...,8.3,8.3,8.2,8.1,8.1,8.2,8.7,8.0,8.6,8.4
114,115,Wreck-It Ralph (2012),7.7,295,125,Animation,Adventure,Comedy,72,165,...,7.6,7.6,7.7,7.4,7.4,7.5,7.4,7.2,7.9,7.6
115,116,X-Men: Days of Future Past (2014),8,560,736,Action,Adventure,Sci-Fi,74,200,...,7.8,7.8,8.0,7.7,7.7,7.9,7.5,7.4,8.1,7.9
116,117,X-Men: First Class (2011),7.8,556,713,Action,Adventure,Sci-Fi,65,160,...,7.7,7.6,7.8,7.6,7.5,7.7,7.6,7.3,7.8,7.7
117,118,Zootopia (2016),8.1,309,474,Animation,Adventure,Comedy,78,150,...,7.8,7.8,8.1,7.8,7.8,8.1,7.7,7.6,8.0,8.0

In [24]:
type(movies)

list

# JSON File

In [25]:
movies_data=pd.read_json("IMDB.json")

In [26]:
movies_data

,X,Title,Rating,TotalVotes,Genre1,Genre2,Genre3,MetaCritic,Budget,Runtime,...,Votes45A,Votes45AM,Votes45AF,VotesIMDB,Votes1000,VotesUS,VotesnUS,Domestic,Foreign,Worldwide
0,1,12 Years a Slave�(2013),8.1,496092,Biography,Drama,History,96,20000000,134 min,...,7.8,7.8,8.1,8.0,7.7,8.3,8,"$56,671,993",131061209,"$187,733,202"
1,2,127 Hours�(2010),7.6,297075,Adventure,Biography,Drama,82,18000000,94 min,...,7.3,7.3,7.5,7.6,7.0,7.7,7.6,"$18,335,230",42403567,"$60,738,797"
2,3,50/50�(2011),7.7,283935,Comedy,Drama,Romance,72,8000000,100 min,...,7.4,7.4,7.5,7.4,7.0,7.9,7.6,"$35,014,192",4173591,"$39,187,783"
3,4,About Time�(2013),7.8,225412,Comedy,Drama,Fantasy,NA,12000000,123 min,...,7.6,7.5,7.8,7.7,6.9,7.8,7.7,"$15,322,921",71777528,"$87,100,449"
4,5,Amour�(2012),7.9,76121,Drama,Romance,,94,8900000,127 min,...,7.9,7.8,8.1,6.6,7.2,7.9,7.8,"$6,739,492",13100000,"$19,839,492"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,114,Whiplash�(2014),8.5,492285,Drama,Music,,88,3300000,107 min,...,8.1,8.1,8.2,8.7,8.0,8.6,8.4,"$13,092,000",35890041,"$48,982,041"
113,115,Wreck-It Ralph�(2012),7.7,295125,Animation,Adventure,Comedy,72,165000000,,...,7.4,7.4,7.5,7.4,7.2,7.9,7.6,"$189,422,889",281800000,"$471,222,889"
114,116,X-Men: Days of Future Past�(2014),8.0,560736,Action,Adventure,Sci-Fi,74,200000000,132 min,...,7.7,7.7,7.9,7.5,7.4,8.1,7.9,"$233,921,534",513941241,"$747,862,775"
115,117,X-Men: First Class�(2011),7.8,556713,Action,Adventure,Sci-Fi,65,160000000,132 min,...,7.6,7.5,7.7,7.6,7.3,7.8,7.7,"$146,408,305",207215819,"$353,624,124"
116,118,Zootopia�(2016),8.1,309474,Animation,Adventure,Comedy,78,150000000,108 min,...,7.8,7.8,8.1,7.7,7.6,8.0,8,"$341,268,248",682515947,"$1,023,784,195"

In [27]:
type(movies_data)

pandas.core.frame.DataFrame

# Pickle File

In [28]:
movies_p=pd.read_pickle("IMDB.p")

In [29]:
movies_p

,X,Title,Rating,TotalVotes,Genre1,Genre2,Genre3,MetaCritic,Budget,Runtime,...,Votes45A,Votes45AM,Votes45AF,VotesIMDB,Votes1000,VotesUS,VotesnUS,Domestic,Foreign,Worldwide
0,1,12 Years a SlaveÂ (2013),8.1,496092,Biography,Drama,History,96.0,20000000.0,134 min,...,7.8,7.8,8.1,8.0,7.7,8.3,8.0,"$56,671,993",131061209,"$187,733,202"
1,2,127 HoursÂ (2010),7.6,297075,Adventure,Biography,Drama,82.0,18000000.0,94 min,...,7.3,7.3,7.5,7.6,7.0,7.7,7.6,"$18,335,230",42403567,"$60,738,797"
2,3,50/50Â (2011),7.7,283935,Comedy,Drama,Romance,72.0,8000000.0,100 min,...,7.4,7.4,7.5,7.4,7.0,7.9,7.6,"$35,014,192",4173591,"$39,187,783"
3,4,About TimeÂ (2013),7.8,225412,Comedy,Drama,Fantasy,NaN,12000000.0,123 min,...,7.6,7.5,7.8,7.7,6.9,7.8,7.7,"$15,322,921",71777528,"$87,100,449"
4,5,AmourÂ (2012),7.9,76121,Drama,Romance,NaN,94.0,8900000.0,127 min,...,7.9,7.8,8.1,6.6,7.2,7.9,7.8,"$6,739,492",13100000,"$19,839,492"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,114,WhiplashÂ (2014),8.5,492285,Drama,Music,NaN,88.0,3300000.0,107 min,...,8.1,8.1,8.2,8.7,8.0,8.6,8.4,"$13,092,000",35890041,"$48,982,041"
113,115,Wreck-It RalphÂ (2012),7.7,295125,Animation,Adventure,Comedy,72.0,165000000.0,NaN,...,7.4,7.4,7.5,7.4,7.2,7.9,7.6,"$189,422,889",281800000,"$471,222,889"
114,116,X-Men: Days of Future PastÂ (2014),8.0,560736,Action,Adventure,Sci-Fi,74.0,200000000.0,132 min,...,7.7,7.7,7.9,7.5,7.4,8.1,7.9,"$233,921,534",513941241,"$747,862,775"
115,117,X-Men: First ClassÂ (2011),7.8,556713,Action,Adventure,Sci-Fi,65.0,160000000.0,132 min,...,7.6,7.5,7.7,7.6,7.3,7.8,7.7,"$146,408,305",207215819,"$353,624,124"
116,118,ZootopiaÂ (2016),8.1,309474,Animation,Adventure,Comedy,78.0,150000000.0,108 min,...,7.8,7.8,8.1,7.7,7.6,8.0,8.0,"$341,268,248",682515947,"$1,023,784,195"

# SQLite File IMDB

In [30]:
import sqlite3

In [31]:
conn = sqlite3.connect("IMDB.sqlite")

In [32]:
conn

In [33]:
df = pd.read_sql_query("select * from IMDB",conn)

In [34]:
df

,X,Title,Rating,TotalVotes,Genre1,Genre2,Genre3,MetaCritic,Budget,Runtime,...,Votes45A,Votes45AM,Votes45AF,VotesIMDB,Votes1000,VotesUS,VotesnUS,Domestic,Foreign,Worldwide
0,1,12 Years a Slave (2013),8.1,496092,Biography,Drama,History,96,20000000,134 min,...,7.8,7.8,8.1,8.0,7.7,8.3,8,"$56,671,993",131061209,"$187,733,202"
1,2,127 Hours (2010),7.6,297075,Adventure,Biography,Drama,82,18000000,94 min,...,7.3,7.3,7.5,7.6,7.0,7.7,7.6,"$18,335,230",42403567,"$60,738,797"
2,3,50/50 (2011),7.7,283935,Comedy,Drama,Romance,72,8000000,100 min,...,7.4,7.4,7.5,7.4,7.0,7.9,7.6,"$35,014,192",4173591,"$39,187,783"
3,4,About Time (2013),7.8,225412,Comedy,Drama,Fantasy,NA,12000000,123 min,...,7.6,7.5,7.8,7.7,6.9,7.8,7.7,"$15,322,921",71777528,"$87,100,449"
4,5,Amour (2012),7.9,76121,Drama,Romance,,94,8900000,127 min,...,7.9,7.8,8.1,6.6,7.2,7.9,7.8,"$6,739,492",13100000,"$19,839,492"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,114,Whiplash (2014),8.5,492285,Drama,Music,,88,3300000,107 min,...,8.1,8.1,8.2,8.7,8.0,8.6,8.4,"$13,092,000",35890041,"$48,982,041"
113,115,Wreck-It Ralph (2012),7.7,295125,Animation,Adventure,Comedy,72,165000000,,...,7.4,7.4,7.5,7.4,7.2,7.9,7.6,"$189,422,889",281800000,"$471,222,889"
114,116,X-Men: Days of Future Past (2014),8.0,560736,Action,Adventure,Sci-Fi,74,200000000,132 min,...,7.7,7.7,7.9,7.5,7.4,8.1,7.9,"$233,921,534",513941241,"$747,862,775"
115,117,X-Men: First Class (2011),7.8,556713,Action,Adventure,Sci-Fi,65,160000000,132 min,...,7.6,7.5,7.7,7.6,7.3,7.8,7.7,"$146,408,305",207215819,"$353,624,124"
116,118,Zootopia (2016),8.1,309474,Animation,Adventure,Comedy,78,150000000,108 min,...,7.8,7.8,8.1,7.7,7.6,8.0,8,"$341,268,248",682515947,"$1,023,784,195"